### ISSUE TITLE
Lightbox Schematic and PCB Check

### ISSUE THREAD

**Issue by conjon1024** [conjon1024/LightSwitch#1]
I posted PDF files of my updated schematic, top layer of PCB, and bottom layer of PCB under Hardware/. I also believe I included the ECAD files of the schematic and PCB under Electronics/.

**Comment by sphaerobolus** [comment]
Maybe you haven't put values in for your pull up and diode-current-limiting resistors. If 100k is your selection, you'll want to re-think that. 100k might be good for the pull up, but definitely no good for the LED current. 

Are you using the internal RC oscillator? If your response to this question is, "huh?" then you're not. If you're not using the internal RC, you'll want an external crystal and capacitors on the 328P, pins 9 and 10. 

Increase the width of traces to at least 12mil, preferably 20mil. 

I'm not keen on the copper pour in between the pads of the SMT components; that's pretty tight if we etch these in house. Maybe increase the clearance in the DRC settings to avoid this.

So if you're using the internal RC and feeling lucky, we could fabricate this. It would be safer with wider traces and clearances.
