### ISSUE TITLE
Updated PCB schematic, board, and code

### ISSUE THREAD

**Issue by conjon1024** [conjon1024/LightSwitch#2]
I updated my schematic and board based on the feedback I received. I also attached my code, which I successfully ran in Chesterfield today. 

I have a few quick questions. I was wondering how I could increase the copper pour in between the surface components. I increased the clearance in the DRC settings but now it just shows up as an error that I am not exactly sure how to fix. In addition, I was wondering what size the mounting holes should be before I put them into the board. Thanks!

**Comment by sphaerobolus** [comment]
A 4-40 screw takes a 0.125" hole. I would go no larger than that. We also have 2-56 screws. 

I wouldn't change your pour. We're finding that students have a difficult time soldering with tight tolerances. Don't worry about the gaps. 

What's up with R1 on the board? You have 5V going to both sides of it, meaning the resistor is effectively not there.

**Comment by conjon1024** [comment]
I just uploaded an updated board based on this feedback! Thank you so much for your quick response!

**Comment by sphaerobolus** [comment]
looks good now

**Comment by conjon1024** [comment]
I just replaced the battery with a pin header so that I do not have to connect the battery directly to the board.
